#!/usr/bin/env python3
"""build.py — Generates install/ files, category indexes, and the README
category table from prompts/ source files.

Usage:
    python3 scripts/build.py              # Full build (validate + generate)
    python3 scripts/build.py --validate   # Validate only, no generation
    python3 scripts/build.py --check      # Check generated files are in sync (CI)

Single-pass and dependency-free. Replaces the original bash implementation,
which forked ~10 subprocesses per file and did not survive contact with a
thousand prompt files.
"""

import os
import re
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROMPTS_DIR = os.path.join(ROOT, "prompts")
INSTALL_DIR = os.path.join(ROOT, "install")
README = os.path.join(ROOT, "README.md")

REQUIRED_FIELDS = ["title", "slug", "category", "tags", "works_with", "severity", "one_liner"]
VALID_SEVERITIES = {"critical", "high", "medium"}
SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2}

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by scripts/build.py — do not edit by hand. "
    "Edit prompts/<category>/<slug>.md and run `make build`. -->"
)


def fail(errors):
    for e in errors:
        print(f"ERROR: {e}")
    print(f"FAILED: {len(errors)} validation errors")
    sys.exit(1)


def strip_quotes(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


def parse_prompt(path):
    """Parse frontmatter and instruction block from a prompt file."""
    with open(path, encoding="utf-8") as f:
        lines = f.read().split("\n")

    # Locate the --- markers: 1st/2nd delimit frontmatter, 3rd/4th the instruction block.
    markers = [i for i, line in enumerate(lines) if line.strip() == "---"]
    fm = {}
    block = ""
    if len(markers) >= 2 and markers[0] == 0:
        for line in lines[markers[0] + 1 : markers[1]]:
            m = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
            if m:
                fm[m.group(1)] = strip_quotes(m.group(2))
    if len(markers) >= 4:
        block = "\n".join(lines[markers[2] + 1 : markers[3]]).strip()

    return fm, block


def get_tags(fm):
    raw = fm.get("tags", "")
    return [t.strip() for t in raw.strip("[]").split(",") if t.strip()]


def collect_prompts():
    """Return list of prompt dicts, sorted by category then slug."""
    prompts = []
    errors = []
    if not os.path.isdir(PROMPTS_DIR):
        fail([f"prompts directory not found: {PROMPTS_DIR}"])

    for category_dir in sorted(os.listdir(PROMPTS_DIR)):
        cat_path = os.path.join(PROMPTS_DIR, category_dir)
        if not os.path.isdir(cat_path):
            continue
        for filename in sorted(os.listdir(cat_path)):
            # README.md is generated; _-prefixed files are category metadata.
            if not filename.endswith(".md") or filename == "README.md" or filename.startswith("_"):
                continue
            path = os.path.join(cat_path, filename)
            fm, block = parse_prompt(path)
            prompts.append(
                {
                    "path": path,
                    "rel": os.path.relpath(path, ROOT),
                    "filename": filename,
                    "basename": filename[:-3],
                    "dir_category": category_dir,
                    "fm": fm,
                    "block": block,
                }
            )
    return prompts


def category_description(category):
    """First non-empty, non-heading line of prompts/<category>/_category.md."""
    path = os.path.join(PROMPTS_DIR, category, "_category.md")
    if not os.path.isfile(path):
        return ""
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                return line
    return ""


def display_category(category):
    special = {"ci-cd": "CI/CD", "api-design": "API Design", "data-and-ml": "Data & ML"}
    if category in special:
        return special[category]
    return " ".join(w.capitalize() for w in category.split("-"))


def validate(prompts):
    errors = []
    seen_slugs = {}
    for p in prompts:
        fm = p["fm"]
        rel = p["rel"]
        for field in REQUIRED_FIELDS:
            if not fm.get(field):
                errors.append(f"{rel} — missing required field: {field}")
        slug = fm.get("slug", "")
        if slug and slug != p["basename"]:
            errors.append(f"{rel} — slug '{slug}' does not match filename '{p['basename']}'")
        category = fm.get("category", "")
        if category and category != p["dir_category"]:
            errors.append(f"{rel} — category '{category}' does not match directory '{p['dir_category']}'")
        severity = fm.get("severity", "")
        if severity and severity not in VALID_SEVERITIES:
            errors.append(f"{rel} — invalid severity '{severity}' (must be critical|high|medium)")
        one_liner = fm.get("one_liner", "")
        if "|" in one_liner:
            errors.append(f"{rel} — one_liner contains '|' which breaks markdown tables")
        if len(one_liner) > 80:
            print(f"WARN: {rel} — one_liner exceeds 80 chars ({len(one_liner)})")
        if not p["block"]:
            errors.append(f"{rel} — no instruction block found (need two --- markers in body)")
        if slug:
            if slug in seen_slugs:
                errors.append(f"{rel} — duplicate slug '{slug}' (also in {seen_slugs[slug]})")
            else:
                seen_slugs[slug] = rel
    return errors


def write_if_changed(path, content):
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            if f.read() == content:
                return
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def generate_install(prompts, install_dir):
    os.makedirs(install_dir, exist_ok=True)
    # Clear stale generated files.
    for f in os.listdir(install_dir):
        if f.endswith(".md"):
            os.remove(os.path.join(install_dir, f))

    all_blocks = []
    essentials = []
    by_category = {}
    for p in prompts:
        slug = p["fm"]["slug"]
        block = p["block"] + "\n"
        with open(os.path.join(install_dir, f"{slug}.md"), "w", encoding="utf-8") as f:
            f.write(block)
        all_blocks.append(p["block"])
        by_category.setdefault(p["fm"]["category"], []).append(p["block"])
        if "essential" in get_tags(p["fm"]):
            essentials.append(p["block"])

    with open(os.path.join(install_dir, "all.md"), "w", encoding="utf-8") as f:
        f.write("\n\n".join(all_blocks) + "\n")
    if essentials:
        with open(os.path.join(install_dir, "essentials.md"), "w", encoding="utf-8") as f:
            f.write("\n\n".join(essentials) + "\n")
    for category, blocks in by_category.items():
        with open(os.path.join(install_dir, f"{category}.md"), "w", encoding="utf-8") as f:
            f.write("\n\n".join(blocks) + "\n")

    count = len([f for f in os.listdir(install_dir) if f.endswith(".md")])
    print(f"Generated {count} install files")


def category_index_content(category, cat_prompts):
    """Generated prompts/<category>/README.md listing every prompt in the category."""
    lines = [GENERATED_HEADER, "", f"# {display_category(category)} Prompts", ""]
    desc = category_description(category)
    if desc:
        lines += [desc, ""]
    lines += [
        f"**{len(cat_prompts)} prompts.** Install the whole category bundle:",
        "",
        "```",
        "Please fetch https://raw.githubusercontent.com/bentheautomator/"
        f"free_ai_prompts_that_dont_suck/main/install/{category}.md "
        "and append its contents to my project instructions file.",
        "```",
        "",
        "| Prompt | Severity | What It Solves | Install |",
        "|--------|----------|----------------|---------|",
    ]
    ordered = sorted(
        cat_prompts,
        key=lambda p: (SEVERITY_ORDER.get(p["fm"]["severity"], 9), p["fm"]["slug"]),
    )
    for p in ordered:
        fm = p["fm"]
        lines.append(
            f"| [{fm['title']}]({fm['slug']}.md) | {fm['severity']} | "
            f"{fm['one_liner']} | [install](../../install/{fm['slug']}.md) |"
        )
    lines.append("")
    return "\n".join(lines)


def generate_category_indexes(prompts, prompts_dir):
    by_category = {}
    for p in prompts:
        by_category.setdefault(p["fm"]["category"], []).append(p)
    for category, cat_prompts in by_category.items():
        path = os.path.join(prompts_dir, category, "README.md")
        write_if_changed(path, category_index_content(category, cat_prompts))
    print(f"Generated {len(by_category)} category indexes")


def readme_table_content(prompts):
    """Compact category summary table for the main README."""
    by_category = {}
    for p in prompts:
        by_category.setdefault(p["fm"]["category"], []).append(p)

    lines = [
        "",
        f"**{len(prompts)} prompts across {len(by_category)} categories.** "
        "Each category page lists every prompt with what it solves.",
        "",
        "| Category | Prompts | What's In It | Install Bundle |",
        "|----------|---------|--------------|----------------|",
    ]
    for category in sorted(by_category):
        desc = category_description(category) or "—"
        lines.append(
            f"| [{display_category(category)}](prompts/{category}/README.md) | "
            f"{len(by_category[category])} | {desc} | [install](install/{category}.md) |"
        )
    lines.append("")
    return "\n".join(lines)


def generate_readme_table(prompts, readme_path):
    with open(readme_path, encoding="utf-8") as f:
        content = f.read()
    start = "<!-- PROMPT_TABLE_START -->"
    end = "<!-- PROMPT_TABLE_END -->"
    if start not in content or end not in content:
        print("WARN: README missing PROMPT_TABLE_START/END markers — skipping table generation")
        return
    pre = content.split(start)[0]
    post = content.split(end)[1]
    new = pre + start + "\n" + readme_table_content(prompts) + end + post
    write_if_changed(readme_path, new)
    print("README category table updated")


def check_sync(prompts):
    """Regenerate everything into temp dirs and diff against the repo."""
    import filecmp
    import shutil

    stale = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_install = os.path.join(tmp, "install")
        generate_install(prompts, tmp_install)
        cmp = filecmp.dircmp(tmp_install, INSTALL_DIR)
        if cmp.left_only or cmp.right_only or cmp.diff_files:
            stale.append("install/")

        for category in {p["fm"]["category"] for p in prompts}:
            cat_prompts = [p for p in prompts if p["fm"]["category"] == category]
            expected = category_index_content(category, cat_prompts)
            path = os.path.join(PROMPTS_DIR, category, "README.md")
            actual = open(path, encoding="utf-8").read() if os.path.isfile(path) else ""
            if expected != actual:
                stale.append(f"prompts/{category}/README.md")

        tmp_readme = os.path.join(tmp, "README.md")
        shutil.copy(README, tmp_readme)
        generate_readme_table(prompts, tmp_readme)
        if open(tmp_readme, encoding="utf-8").read() != open(README, encoding="utf-8").read():
            stale.append("README.md")

    if stale:
        print("STALE: generated files out of sync: " + ", ".join(stale))
        print("Run 'make build' to regenerate.")
        sys.exit(1)
    print("Generated files are in sync")


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "build"
    prompts = collect_prompts()
    errors = validate(prompts)

    if mode in ("--validate", "--validate-only"):
        if errors:
            fail(errors)
        print(f"All {len(prompts)} prompts valid")
        return

    if errors:
        fail(errors)

    if mode == "--check":
        check_sync(prompts)
        return

    generate_install(prompts, INSTALL_DIR)
    generate_category_indexes(prompts, PROMPTS_DIR)
    generate_readme_table(prompts, README)
    print(f"Build complete — {len(prompts)} prompts")


if __name__ == "__main__":
    main()
